version: "3.8"
services:
  route-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      GIS_API_KEY: ${GIS_API_KEY}
      LLM_API_KEY: ${LLM_API_KEY}
    restart: unless-stopped
